language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    # php deps
    - composer self-update
    - composer install --dev

script: ./bin/phpunit -v
